name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ESLINT_USE_FLAT_CONFIG: false
    steps: 
        - name: Check out repository code
          uses: actions/checkout@v3
          
        - name: Setup Node.js environment
          uses: actions/setup-node@v4.1.0
          with:
            node-version: 20
            
        - name: Install yarn
          run: yarn install --frozen-lockfile      
          
        - name: Lint with yarn
          run: yarn lint
          
        - name: Docker Login
          uses: docker/login-action@v3.3.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            logout: true
          
        - name: Build and push the Docker image
          run: | 
            docker build . -t tincirci/webapp
            docker push tincirci/webapp
          


          
                
          
