name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ESLINT_USE_FLAT_CONFIG: false
    steps: 
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Setup Node.js environment
          uses: actions/setup-node@v4.1.0
          with:
            node-version: 20
        - name: Install yarn
          run: yarn install --frozen-lockfile      
        - name: Lint with yarn
          run: yarn lint            
        - name: Build the Docker image
          run: docker build . -t tincirci/webapp
          
          
