name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Setup Node.js environment
          uses: actions/setup-node@v4.1.0
          with:
            # Set always-auth in npmrc.
            node-version: 20
        - name: Install yarn
          run: yarn install
        - name: Lint with yarn
          run: yarn lint          
          
          
          
